# Generated by Django 4.2.1 on 2024-07-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='special_occasion',
            field=models.CharField(choices=[('Bday', 'Birthday'), ('Anv.', 'Anniversary'), ('Other', 'Other')], max_length=20),
        ),
    ]
