# Generated by Django 4.2.1 on 2024-07-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_booking_special_occasion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'meal_day', 'meal_time', 'special_occasion'), name='unique_booking'),
        ),
    ]
