# Generated by Django 4.2.1 on 2024-08-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_alter_review_booking_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
